language: csharp
solution: Store.sln
mono: none
dotnet: 2.0.3
dist: trusty
script:
 - dotnet restore
 - dotnet build ./Store.Model/
 - dotnet build ./Store/
 - dotnet build ./Store.Client/
 - dotnet build ./Store.Client.Example/
 - dotnet build ./Store.Test/
